version: '3.4'

services:
  worker:
    build: .
    image: &img worker
    command: celery -A tasks worker --loglevel=info
    environment: &env
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - SCHEDULE=3
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes:
      - ./:/scrapper

  beat:
    build: .
    image: *img
    command: celery -A worker beat --loglevel=INFO
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ./:/scrapper

  rabbitmq:
    image: rabbitmq:3.7.8
